locales:
  waw:
    name: Waiwai Keyboards
    description: >-
      Mobile OS keyboards for the Waiwai language from the Divvun group
      at UiT.
  en:
    name: Waiwai Keyboards
    description: >-
      Mobile OS keyboards for the Waiwai language from the Divvun group
      at UiT.
  nb:
    name: Waiwai tastatur
    description: Mobiltastatur for Waiwai fra Divvun-gruppa.
author: 'The Divvun Group, UiT Norgga 치rktala코 universitehta'
copyright: (c) 2017 Divvun/Giellatekno/UiT
email: feedback@divvun.no
organisation: UiT Norgga 치rktala코 universitehta
